### ISSUE TITLE
Table and record improvements checklist for RacketCon 2019 hackathon

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/rebellion#144]
As part of the Data Science hackathon at RacketCon 2019, I'd like to improve the `rebellion/collection/record` and `rebellion/collection/table` modules. Here's a checklist of ideas:

- [ ] Implement `(record-set rec #:<kw> v)`
- [ ] Implement `(record-set-field rec record-field?)`
- [ ] Implement `into-record`, `for/record`, and `for*/record`
- [ ] Implement `in-record-fields`, `in-record`, `in-record-keys`, and `in-record-values`
- [ ] Implement `record-fields` (set-of-fields view)
- [ ] Implement `(record-ref-option rec #:<kw>)` (returns an `option?`)
- [ ] Implement `(record-remove rec #:<kw>)`
- [ ] Implement `(record-update rec #:<kw> f failure-result)`
- [ ] Implement `(record-remove-all rec keys)`
- [ ] Implement `(table-add table record)`
- [ ] Implement `into-table`, `for/table`, and `for*/table`
- [ ] Implement `(in-table-rows table)`
- [ ] Implement `(in-table-column table #:<kw>)`
- [ ] Implement `(table-reduce table #:<kw> reducer ...)` and possibly `(record-reducer #:<kw> reducer ...)`
